### PR TITLE
Ocaml backend refactoring + test

### PR DESCRIPTION
**Pull request by taktoa**
As far as I can tell these commits don't break anything except by adding a test that currently fails (OcamlBackendTest.java).

edit: I've commented out the failing code in OcamlBackendTest, so this PR shouldn't break anything

### CODE REVIEW

**Comment by dwightguth** [comment]
This isn't really doing anything to make the code easier to deal with. You have added a lot of new variables and functions, but each one seems to be used in exactly one location. Such a degree of normalization isn't really helpful. The purpose of functions and constants is to abstract out information that is shared across multiple call sites.

Can you come to the RV office sometime this week so we can discuss exactly the best way to use your time so that it is not wasted in overlap with my own work? I think what I would ultimately like to see is work in parallel on a Scala backend which performs similar work to the Ocaml backend, but in Scala and operating over an AST representation of Scala code.

@andreistefanescu what day of the week might you be in the office so that you could join the meeting as well?

**Comment by taktoa** [comment]
Alright, I can come in pretty much any time this week; it's up to you.

Since I wasn't making much progress on getting that unit test to work and was worried about duplicating work between us, I (as well as Sebastian @sebmathguy) actually decided to just start a separate backend for generic functional languages (https://github.com/taktoa/k/tree/func-backend).

Having it generate Scala should definitely be doable - Sebastian is working on a generic functional language AST that should only implement things that are in nearly all functional languages (function signatures / definitions, ADT definitions, patterns, basic expressions - speedup can later be obtained by adding more specific interfaces could be added for e.g. map lookup). Once we have such an AST, we just need to pretty-print it as Scala.

**Comment by dwightguth** [comment]
I am looking at what you are working on and it doesn't look like you are starting from the right infrastructure. This code seems to be based on the old pipeline that we are trying to deprecate. I would prefer to sync up before too much more work goes into this because I want to make sure you are working on the right things. Can you come in sometime in the morning tomorrow then?

**Comment by taktoa** [comment]
Ah, I was wondering if the fact that we weren't going through org.kframework.kompile.Kompile / KORE would be a problem. Most of the work we've done today should be transferable to the KORE pipeline. Tomorrow morning is doable, though afternoon is easier if possible.

**Comment by dwightguth** [comment]
Afternoon should be fine, as long as it's not too late. Maybe 1pm?

**Comment by taktoa** [comment]
That sounds fine.

**Comment by andreistefanescu** [comment]
Tomorrow at 1 sounds good.

Andrei

**Pull request closed without merging**
